### PR TITLE
Introduce basic CI and fix typo in previous PR

### PR DESCRIPTION
**Pull request by Jakuje**

### CODE REVIEW

**Comment by Jakuje** [comment]
Turns out it would require some signing certificate too so not sure if it is a good idea. Will leave up to you what to do with this if you would find it useful or just fix the API:

https://github.com/Jakuje/OpenSCToken/actions/runs/3113235418/jobs/5047609897

**Comment by Jakuje** [comment]
@frankmorgner can you have a look?

**Comment by frankmorgner** [comment]
Yes, indeed I've set up the signing credentials over in OpenSC. This is kind of complicated to set up, so I'd like to avoid it for now...

**Comment by Jakuje** [comment]
ok so please merge the first commit so we can unbreak the OpenSC build (did not test it but I believe it was wrong in the last PR).

**Comment by frankmorgner** [comment]
done, thank you

**Pull request closed without merging**
